# Generated by Django 5.1.3 on 2025-01-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_duration', models.CharField(max_length=200)),
                ('movie_year', models.CharField(max_length=200)),
                ('movie_image', models.ImageField(upload_to='pics')),
                ('movie_description', models.CharField(max_length=500)),
            ],
        ),
    ]
