# Generated by Django 5.1.3 on 2025-01-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movietapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie',
            new_name='moviet',
        ),
    ]
