# Generated by Django 5.1.3 on 2025-01-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietapp', '0002_rename_movie_moviet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviet',
            name='movie_duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='moviet',
            name='movie_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='moviet',
            name='movie_year',
            field=models.CharField(max_length=50),
        ),
    ]
